package crypto

import (
	"crypto/ecdsa"
	"crypto/sha256"
	"crypto/x509"
	"encoding/base64"
	"fmt"
)

// VerifyAppleSecureEnclaveSignature verifies a P-256 ECDSA signature generated by an iPhone's Secure Enclave
func VerifyAppleSecureEnclaveSignature(
	publicKeyBase64 string,
	taskID string,
	amountCents int64,
	deadlineUTC string,
	signatureBase64 string,
) (bool, error) {
	if publicKeyBase64 == "" || signatureBase64 == "" {
		return false, fmt.Errorf("missing public key or signature")
	}

	// 1. Decode user's Public Key from DER/Base64
	pubKeyBytes, err := base64.StdEncoding.DecodeString(publicKeyBase64)
	if err != nil {
		return false, fmt.Errorf("failed to decode public key base64: %w", err)
	}

	pubKeyInterface, err := x509.ParsePKIXPublicKey(pubKeyBytes)
	if err != nil {
		return false, fmt.Errorf("failed to parse PKIX public key: %w", err)
	}

	ecdsaPubKey, ok := pubKeyInterface.(*ecdsa.PublicKey)
	if !ok {
		return false, fmt.Errorf("public key is not ECDSA")
	}

	// 2. Decode the DER/ASN.1 signature from the iPhone
	sigBytes, err := base64.StdEncoding.DecodeString(signatureBase64)
	if err != nil {
		return false, fmt.Errorf("failed to decode signature base64: %w", err)
	}

	// 3. Reconstruct canonical payload & compute SHA256
	payload := fmt.Sprintf("taskId:%s|amountCents:%d|deadlineUtc:%s", taskID, amountCents, deadlineUTC)
	hash := sha256.Sum256([]byte(payload))

	// 4. Cryptographic ECDSA P-256 verification
	isValid := ecdsa.VerifyASN1(ecdsaPubKey, hash[:], sigBytes)
	return isValid, nil
}
